server:
  port: 8081
spring:
  
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:covid_analysis;INIT=CREATE SCHEMA IF NOT EXISTS covid_analysis
    driver-class-name: org.h2.Driver